development:
  adapter: postgresql
  database: railswiki_development
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: railswiki_test
  host: localhost
  username: postgres
  password: postgres
